on: push

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        python-version: [2.7, 3.6, 3.9]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Dry run
        run: sh install-citc.sh
